server:
  port: 8080

spring:
  application:
    name: AI2502TeamPro

  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false #spring.thymeleaf.cache

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roofy?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser
    password: 1234

  security:
    # Oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxxxx
            client-secret: xxxxxxx
            scope:
              - email
              - profile

  servlet:
    multipart:
      # 파일 크기 제한 설정
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
  oauth2:
    password: 1234

    #kakao 로그인 관련 세팅값
    kakao:
      client-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # 앱 키
      redirect-uri: xxxxxxxxxx # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청

  upload:
    path: upload

  pagination:
    write_pages: 10
    page_rows: 10