server:
  port: 8080

spring:
  application:
    name: AI2502TeamPro

  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false #spring.thymeleaf.cache

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user1?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user1
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml